// https://github.com/ebi-webcomponents/react-msa-viewer/tree/master/src/colorschemes
export enum MsaColorScheme {
  ALIPHATIC = 'aliphatic',
  AROMATIC = 'aromatic',
  BURIED = 'buried',
  BURIED_INDEX = 'buried_index',
  CHARGED = 'charged',
  CINEMA = 'cinema',
  CLUSTAL2 = 'clustal2',
  CLUSTAL = 'clustal',
  HELIX_PROPENSITY = 'helix_propensity',
  HYDRO = 'hydro',
  LESK = 'lesk',
  MAE = 'mae',
  NEGATIVE = 'negative',
  NUCLEOTIDE = 'nucleotide',
  POLAR = 'polar',
  POSITIVE = 'positive',
  PURINE = 'purine',
  PURINE_PYRIMIDINE = 'purine_pyrimidine',
  SERINE_THREONINE = 'serine_threonine',
  STRAND_PROPENSITY = 'strand_propensity',
  TAYLOR = 'taylor',
  TURN_PROPENSITY = 'turn_propensity',
  ZAPPO = 'zappo',
  CONSERVATION = 'conservation',
}

export const msaColorSchemeToString = {
  [MsaColorScheme.CONSERVATION]: 'Similarity',
  [MsaColorScheme.NEGATIVE]: 'Negative',
  [MsaColorScheme.POSITIVE]: 'Positive',
  [MsaColorScheme.ALIPHATIC]: 'Aliphatic',
  [MsaColorScheme.AROMATIC]: 'Aromatic',
  [MsaColorScheme.CHARGED]: 'Charged',
  [MsaColorScheme.POLAR]: 'Polar',
  [MsaColorScheme.SERINE_THREONINE]: 'Serine Threonine',
  [MsaColorScheme.BURIED_INDEX]: 'Buried Index',
  [MsaColorScheme.CLUSTAL]: 'Clustal',
  [MsaColorScheme.CLUSTAL2]: 'Clustal 2',
  [MsaColorScheme.CINEMA]: 'Cinema',
  [MsaColorScheme.HELIX_PROPENSITY]: 'Helix Propensity',
  [MsaColorScheme.HYDRO]: 'Hydro',
  [MsaColorScheme.LESK]: 'Lesk',
  [MsaColorScheme.MAE]: 'Mae',
  [MsaColorScheme.NUCLEOTIDE]: 'Nucleotide',
  [MsaColorScheme.PURINE_PYRIMIDINE]: 'Purine Pyrimidine',
  [MsaColorScheme.STRAND_PROPENSITY]: 'Strand Propensity',
  [MsaColorScheme.TAYLOR]: 'Taylor',
  [MsaColorScheme.TURN_PROPENSITY]: 'Turn Propensity',
  [MsaColorScheme.ZAPPO]: 'Zappo',
};
